apiVersion: batch/v1
kind: Job
metadata:
  name: attach-to-tangle
spec:
  parallelism: 1
  template:
    metadata:
      name: attach-to-tangle
    spec:
      containers:
      - name: c
        image: worker:alpha
        env:
        - name: BROKER_URL
          value: amqp://guest:guest@rabbitmq-service:5672
        - name: INCOMING_QUEUE
          value: attach-to-tangle
        - name: CCURL_PATH
          value: /opt
      restartPolicy: OnFailure
